[Rainmeter]
Group=
RightMouseDoubleClickAction=
OnCloseAction=
SkinWidth=[#ScreenAreaWIDTH]
SkinHeight=[#ScreenAreaHEIGHT]
BackgroundMode=2
SolidColor=0,0,0,1
LeftMouseDownAction=[]
OnRefreshAction=[!Zpos 2][!Draggable 0][!KeepOnScreen 0][!Move 0 0][!ShowFade]

DefaultSavePosition=1
DefaultAlwaysOnTop=2
DefaultDraggable=0
DefaultSnapEdges=1
DefaultStartHidden=1
DefaultAlphaValue=255
DefaultHideOnMouseOver=0
DefaultFadeDuration=105
DefaultClickThrough=0
DefaultKeepOnScreen=1
DefaultAutoSelectScreen=1
